name: python
version: 5.1.0
schema: 1
scm: github.com/pubnub/python
changelog:
  - version: v5.1.0
    date: Mar 8, 2021
    changes:
      -
        text: "BREAKING CHANGE: Add randomized initialization vector usage by default for data encryption / decryption in publish / subscribe / history API calls."
        type: feature
  - version: v5.0.1
    date: Feb 4, 2021
    changes:
      -
        text: "User defined 'origin'(custom domain) value was not used in all required places within this SDK."
        type: feature
  - version: v5.0.0
    date: Jan 21, 2021
    changes:
      -
        text: "Apart from bringing the whole SDK up to date, support for Tornado and Twisted was removed and dependiecies were simplified."
        type: improvement
  - version: v4.8.1
    date: Jan 18, 2021
    changes:
      -
        text: "New v3 History endpoint allows to fetch 100 messages per channel."
        type: feature
  - version: v4.8.0
    date: Dec 9, 2020
    changes:
      -
        text: "Objects v2 implementation added to the PythonSDK with additional improvements to the test isolation within whole test suite."
        type: feature
  - version: v4.7.0
    date: Nov 19, 2020
    changes:
      -
        text: "Within this release problems with double PAM calls encoding and Publish oriented bugs were fixed."
        type: bug
  - version: v4.6.1
    date: Oct 27, 2020
    changes:
      -
        text: "Passing uuid to the get_state endpoint call added."
        type: bug
  - version: v4.6.0
    date: Oct 22, 2020
    changes:
      -
        text: "File Upload added to the Python SDK."
        type: feature
  - version: v4.5.4
    date: Sep 29, 2020
    changes:
      -
        text: "Add `suppress_leave_events` configuration option which can be used to opt-out presence leave call on unsubscribe."
        type: feature
      -
        text: "Log out message decryption error and pass received message with `PNDecryptionErrorCategory` category to status listeners."
        type: improvement
  - version: v4.5.3
    date: Aug 10, 2020
    changes:
      -
        text: "Allocating separate thread that basically waits a certain amount of time to clean telemetry data is a waste of memory/OS data structures. Cleaning mentioned data can be incorporated into regular logic."
        type: improvement
  - version: v4.5.2
    date: May 29, 2020
    changes:
      -
        text: "Fix bug with max message count parameter for Fetch Messages endpoint. Rename maximum_per_channel parameter to count for Fetch Messages, keeping the old name for compatibility."
        type: bug
  - version: v4.5.1
    date: May 4, 2020
    changes:
      -
        text: "Using SSL by default from the Python SDK to be more consistent and encourage best practices."
        type: bug
  - version: v4.5.0
    date: Feb 27, 2020
    changes:
      - type: feature
        text: Implemented Objects Filtering API
  - version: v4.4.0
    date: Feb 20, 2020
    changes:
      - type: feature
        text: Add support for APNS2 Push API
  - version: v4.3.0
    date: Jan 28, 2020
    changes:
      - type: feature
        text: Implemented Message Actions API
      - type: feature
        text: Implemented Fetch Messages API
      - type: feature
        text: Added 'include_meta' to history()
      - type: feature
        text: Added 'include_meta' to fetch_messages()
      - type: feature
        text: Added 'include_message_actions' to fetch_messages()
  - version: v4.2.1
    date: Jan 9, 2020
    changes:
      - type: bug
        text: Excluded the tilde symbol from being encoded by the url_encode method to fix invalid PAM signature issue.
  - version: v4.2.0
    date: Dec 24, 2019
    changes:
      - type: improvement
        text: Introduced delete permission to Grant endpoint. Migrated to v2 endpoints for old PAM methods.
      - type: feature
        text: Added TokenManager and GrantToken method.
      - type: improvement
        text: Resolved warnings caused by the use of deprecated methods.
      - type: bug
        text: Removed Audit tests.
      - type: bug
        text: Resolved incorrectly reported SDK version.
  - version: v4.1.7
    date: Dec 2, 2019
    changes:
      - type: improvement
        text: Add users join, leave and timeout fields to interval event
  - version: v4.1.6
    date: Aug 24, 2019
    changes:
      - type: improvement
        text: implement Objects API
  - version: v4.1.5
    date: Aug 9, 2019
    changes:
      - type: improvement
        text: implement Signal
  - version: v4.1.4
    date: Apr 10, 2019
    changes:
      - type: improvement
        text: implement Fire
  - version: v4.1.3
    date: Feb 25, 2019
    changes:
      - type: improvement
        text: implement history Message Counts
  - version: v4.1.2
    date: Sep 20, 2018
    changes:
      - type: improvement
        text: Rename await to pn_await
  - version: v4.1.1
    date: Sep 11, 2018
    changes:
      - type: improvement
        text: Rename async to pn_async
  - version: v4.1.0
    date: Jan 18, 2018
    changes:
      - type: improvement
        text: Add history delete
      - type: improvement
        text: Add telemetry manager
      - type: bug
        text: Fix linter warnings
      - type: bug
        text: Fix plugins versions and remove unused plugins
  - version: v4.0.13
    date: Jun 14, 2017
    changes:
      - type: improvement
        text: Added daemon option for PNConfig
  - version: v4.0.12
    date:
    changes:
      - type: bug
        text: Fixed issues with managing push notifications
  - version: v4.0.11
    date: May 22, 2017
    changes:
      - type: bug
        text: Fix typo on announce_status.
  - version: v4.0.10
    date: Mar 23, 2017
    changes:
      - type: bug
        text: Fix aiohttp v1.x.x and v2.x.x compatibility
  - version: v4.0.9
    date: Mar 10, 2017
    changes:
      - type: bug
        text: Fix missing encoder for path elements
      - type: feature
  - version: v4.0.8
    date: Feb 17, 2017
    changes:
      - type: feature
        text: Support log_verbosity in pnconfiguration to enable HTTP logging.
  - version: v4.0.7
    date: Feb 5, 2017
    changes:
      - type: bug
        text: Handle interval presence messages gracefully if they do not contain a UUID.
      - type: feature
        text: Support custom cryptography module when using GAE
      - type: improvement
        text: designate the request thread as non-daemon to keep the SDK running.
  - version: v4.0.6
    date: Jan 21, 2017
    changes:
      - type: bug
        text: Fix on state object type definition.
  - version: v4.0.5
    date: Jan 4, 2017
    changes:
      - type: improvement
        text: new pubnub domain
      - type: improvement
        text: native demo app
      - type: improvement
        text: fixed HTTPAdapter config
      - type: improvement
        text: add a new Python 3.6.0 config to travis builds
      - type: improvement
        text: fix blocking Ctrl+C bug
  - version: v4.0.4
    date: Dec 21, 2016
    changes:
      - type: improvement
        text: Add reconnection managers
  - version: v4.0.3
    date:
    changes:
      - type: improvement
        text: do not strip plus sign when encoding message.
  - version: v4.0.2
    date: Nov 14, 2016
    changes:
      - type: improvement
        text: Adjusting maximum pool size for requests installations
      - type: improvement
        text: Adding Publisher UUID
  - version: v4.0.1
    date: Nov 8, 2016
    changes:
      - type: improvement
        text: Fixing up packaging configuration for py3
  - version: v4.0.0
    date: Nov 2, 2016
    changes:
      - type: improvement
        text: Initial Release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-GRANT-MANAGE
    - ACCESS-GRANT-DELETE
    - ACCESS-GRANT-V3
    - ACCESS-TOKEN-MANAGEMENT
    - ACCESS-SECRET-KEY-ALL-ACCESS    
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  others:
    - TELEMETRY
    - CREATE-PUSH-PAYLOAD
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
    - PUSH-TYPE-APNS
    - PUSH-TYPE-APNS2
    - PUSH-TYPE-GCM
    - PUSH-TYPE-FCM
    - PUSH-TYPE-MPNS
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
    - STORAGE-FETCH-WITH-MESSAGE-ACTIONS
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-SIGNAL-LISTENER
    - SUBSCRIBE-USER-LISTENER
    - SUBSCRIBE-SPACE-LISTENER
    - SUBSCRIBE-MEMBERSHIP-LISTENER
    - SUBSCRIBE-MESSAGE-ACTIONS-LISTENER
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-USER
    - OBJECTS-GET-USERS
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACE
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-MANAGE-MEMBERSHIPS
    - OBJECTS-MANAGE-MEMBERS
    - OBJECTS-JOIN-SPACES
    - OBJECTS-UPDATE-MEMBERSHIPS
    - OBJECTS-LEAVE-SPACES
    - OBJECTS-GET-MEMBERS
    - OBJECTS-ADD-MEMBERS
    - OBJECTS-UPDATE-MEMBERS
    - OBJECTS-REMOVE-MEMBERS
    - OBJECTS-FILTERING
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE

supported-platforms:
  -
    version: PubNub Python SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
    editors:
      - python 2.7.13
      - python 3.4.5
      - python 3.5.2
      - python 3.6.0
      - pypy
  -
    version: PubNub Python Tornado SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
    editors:
      - python 2.7.13
      - python 3.4.5
      - python 3.5.2
      - python 3.6.0
      - pypy
  -
    version: PubNub Python Asyncio SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
    editors:
      - python 3.4.5
      - python 3.5.2
      - python 3.6.0
  -
    version: PubNub Python Twisted SDK
    platforms:
      - Linux 2.6 or later, amd64, 386.
    editors:
      - python 2.7.13
